In [1]:
import numpy as np
from aspired import image_reduction
from aspired import spectral_reduction
from astropy.io import fits
import plotly.io as pio
pio.renderers.default = "notebook"

Case b)

The FITS structure of the science frame is non-standard for long-slit spectra: 10 frames are stored in a data cube using the third axis for time information. ASPIRED cannot understand the given data, so a None would be stored and continue with the process as much as possible, hence when trying to view the plot, it is empty.

The shapes of this data cube is as follow:

In [2]:
science_fits = fits.open('data/spectre_HD20041_00038.fits')

In [3]:
print('Case 1: ', type(science_fits), np.shape(science_fits))
print('Case 2: ', type(science_fits[0]), np.shape(science_fits[0]))
print('Case 3: ', type(science_fits[0].data), np.shape(science_fits[0].data))
print('Case 4: ', type(science_fits[0].data[0]), np.shape(science_fits[0].data[0]))

Case 1:  <class 'astropy.io.fits.hdu.hdulist.HDUList'> (1,)
Case 2:  <class 'astropy.io.fits.hdu.image.PrimaryHDU'> (10, 1001, 2048)
Case 3:  <class 'numpy.ndarray'> (10, 1001, 2048)
Case 4:  <class 'numpy.ndarray'> (1001, 2048)


ASPIRED is now checking extra data structure, it can understand all these three formats. In case 1, it will enter one level and continue the operation. In the second case, when ASPIRED reads a 3-dimensional HDU data, it will only take the first array of data and throw a warning. In the third case, it is reading a 3-dimensional data structure of numpy array, where only the first array of data will be read and throw a warning. In the last case, it is the expected 2D array structure so it always work. Please also note the number of square brackets in the 4 cases:

In [4]:
# Case 1 working - with the header, the gain and exposure time can be found. Readnoise and seeing values are not present in the header.
science_frame_twodspec = spectral_reduction.TwoDSpec(science_fits)
print(science_frame_twodspec.img)

# Reset
science_frame_twodspec = None

[[[20.466667 20.466667 19.866667 ... 20.       19.666666 20.466667]
  [20.133333 20.133333 20.2      ... 20.       20.333334 20.533333]
  [20.       20.266666 20.       ... 20.466667 20.266666 20.333334]
  ...
  [20.133333 20.133333 20.6      ... 20.       20.       20.333334]
  [20.2      20.6      20.266666 ... 20.666666 19.933332 20.133333]
  [20.533333 19.866667 20.333334 ... 20.333334 20.066668 19.8     ]]

 [[20.066668 20.066668 19.933332 ... 20.       20.2      20.2     ]
  [20.133333 20.6      20.733334 ... 19.933332 20.4      19.733334]
  [20.466667 20.133333 20.333334 ... 20.466667 19.933332 20.4     ]
  ...
  [20.466667 20.333334 20.866667 ... 20.066668 20.266666 20.6     ]
  [20.4      20.733334 20.133333 ... 20.333334 20.2      20.266666]
  [20.4      19.933332 20.8      ... 20.333334 20.133333 20.533333]]

 [[20.666666 20.466667 20.266666 ... 20.6      20.266666 20.133333]
  [20.4      20.066668 20.533333 ... 20.333334 20.533333 19.933332]
  [20.333334 20.4      20.      

In [5]:
# Case 2 - with the header, the gain and exposure time can be found. Readnoise and seeing values are not present in the header.
science_frame_twodspec = spectral_reduction.TwoDSpec(science_fits[0])
print(science_frame_twodspec.img)

# Reset
science_frame_twodspec = None

[[[20.466667 20.466667 19.866667 ... 20.       19.666666 20.466667]
  [20.133333 20.133333 20.2      ... 20.       20.333334 20.533333]
  [20.       20.266666 20.       ... 20.466667 20.266666 20.333334]
  ...
  [20.133333 20.133333 20.6      ... 20.       20.       20.333334]
  [20.2      20.6      20.266666 ... 20.666666 19.933332 20.133333]
  [20.533333 19.866667 20.333334 ... 20.333334 20.066668 19.8     ]]

 [[20.066668 20.066668 19.933332 ... 20.       20.2      20.2     ]
  [20.133333 20.6      20.733334 ... 19.933332 20.4      19.733334]
  [20.466667 20.133333 20.333334 ... 20.466667 19.933332 20.4     ]
  ...
  [20.466667 20.333334 20.866667 ... 20.066668 20.266666 20.6     ]
  [20.4      20.733334 20.133333 ... 20.333334 20.2      20.266666]
  [20.4      19.933332 20.8      ... 20.333334 20.133333 20.533333]]

 [[20.666666 20.466667 20.266666 ... 20.6      20.266666 20.133333]
  [20.4      20.066668 20.533333 ... 20.333334 20.533333 19.933332]
  [20.333334 20.4      20.      

In [6]:
# Case 3 - without any header, nothing cannot be found.
science_frame_twodspec = spectral_reduction.TwoDSpec(science_fits[0].data)
print(science_frame_twodspec.img)

# Reset
science_frame_twodspec = None

[[[307. 307. 298. ... 300. 295. 307.]
  [302. 302. 303. ... 300. 305. 308.]
  [300. 304. 300. ... 307. 304. 305.]
  ...
  [302. 302. 309. ... 300. 300. 305.]
  [303. 309. 304. ... 310. 299. 302.]
  [308. 298. 305. ... 305. 301. 297.]]

 [[301. 301. 299. ... 300. 303. 303.]
  [302. 309. 311. ... 299. 306. 296.]
  [307. 302. 305. ... 307. 299. 306.]
  ...
  [307. 305. 313. ... 301. 304. 309.]
  [306. 311. 302. ... 305. 303. 304.]
  [306. 299. 312. ... 305. 302. 308.]]

 [[310. 307. 304. ... 309. 304. 302.]
  [306. 301. 308. ... 305. 308. 299.]
  [305. 306. 300. ... 300. 301. 307.]
  ...
  [304. 308. 305. ... 311. 296. 301.]
  [308. 305. 302. ... 301. 310. 298.]
  [307. 306. 299. ... 309. 297. 303.]]

 ...

 [[304. 299. 309. ... 302. 301. 309.]
  [302. 306. 297. ... 307. 303. 303.]
  [305. 301. 305. ... 301. 305. 301.]
  ...
  [306. 304. 297. ... 298. 304. 306.]
  [303. 308. 296. ... 299. 306. 301.]
  [303. 311. 303. ... 299. 303. 298.]]

 [[306. 300. 303. ... 299. 299. 298.]
  [307. 306.

In [7]:
# Case 4 - without any header, nothing cannot be found.
science_frame_twodspec = spectral_reduction.TwoDSpec(science_fits[0].data[0])
print(science_frame_twodspec.img)

# Reset
science_frame_twodspec = None

[[307. 307. 298. ... 300. 295. 307.]
 [302. 302. 303. ... 300. 305. 308.]
 [300. 304. 300. ... 307. 304. 305.]
 ...
 [302. 302. 309. ... 300. 300. 305.]
 [303. 309. 304. ... 310. 299. 302.]
 [308. 298. 305. ... 305. 301. 297.]]


Case d

After including more data structure trapping, this is now working. I have downgraded some of the errors to warnings. The 5 levels of errors: DEBUG, INFO, WARNING, ERROR and CRITICAL. The first two are obvious. In my standard, WARNING is when some suboptimal operations are performed, which can lead to wrong results but it should complete all operations. ERROR is when something is wrong, but the software can try to proceed as much as possible, it is unlikely to produce anything useful, but it can exit without blocking the script. CRITICAL is when operations that will terminate immediately because it cannot identify any alternative solution, usually happen in the data ingestion stage. The logging system is far from complete, even some of the most frequently used functions are not coming with a complete set of logging.

In [8]:
science_frame = image_reduction.ImageReduction('data/test.txt', exptime_dark=15., log_level='INFO')
science_frame.reduce()
science_frame_twodspec = spectral_reduction.TwoDSpec(science_frame, cosmicray=True)

In [9]:
hgar_fits = fits.open('data/spectre_hgar_00028.fits')

In [10]:
science_frame_twodspec.add_arc(hgar_fits[0].data[0])

In [11]:
print(science_frame_twodspec.arc)

[[300. 302. 311. ... 310. 303. 300.]
 [310. 305. 306. ... 306. 303. 305.]
 [304. 309. 309. ... 308. 302. 308.]
 ...
 [308. 309. 303. ... 306. 309. 312.]
 [302. 308. 306. ... 306. 307. 307.]
 [302. 306. 310. ... 310. 311. 306.]]
